services:
  prueba-ufinet-db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: prueba-ufinet-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Legato1218*"
    ports:
      - "1434:1433"
    volumes:
      - /home/legato/sql-server-dockerized:/var/opt/mssql
    networks:
      - app-network

  prueba-ufinet-backend:
    image: spring-backend
    container_name: prueba-ufinet-backend
    depends_on:
      - prueba-ufinet-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://prueba-ufinet-db:1433;databaseName=bookapp;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Legato1218*
    ports:
      - "8080:8080"
    networks:
      - app-network


  prueba-ufinet-frontend:
    image: react-frontend
    container_name: prueba-ufinet-frontend
    depends_on:
      - prueba-ufinet-backend
    ports:
      - "5173:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
